package pt.upa.security.ws;

import static org.junit.Assert.*;

import org.junit.Test;

import pt.upa.transporter.ws.JobView;

public class RequestJobPriceAttackIT extends BaseIT {
  @Test
  public void testRequestJobModifyPrice() throws Exception{
    String  city1 = "Lisboa",
        city2 = "Coimbra";

    transporter1.setIsTest(1);
    JobView job = transporter1.requestJob(city1, city2, 50);
    assertNull(job);
    System.out.println("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY");
    transporter1.setIsTest(0);
  }
} 
